# Generated by Django 5.2.6 on 2025-10-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
