# Generated by Django 5.2.6 on 2025-10-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_update_at_page_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='チェックボタン'),
        ),
    ]
